//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v8.17.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Umbraco.Web.PublishedModels
{
	// Mixin Content Type with alias "heroBannerComposition"
	/// <summary>HeroBannerComposition</summary>
	public partial interface IHeroBannerComposition : IPublishedContent
	{
		/// <summary>HeroBannerIImage</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.17.0")]
		global::Umbraco.Core.Models.MediaWithCrops HeroBannerIimage { get; }

		/// <summary>HeroBannerSubtitle</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.17.0")]
		string HeroBannerSubtitle { get; }

		/// <summary>HeroBannerTitle</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.17.0")]
		string HeroBannerTitle { get; }
	}

	/// <summary>HeroBannerComposition</summary>
	[PublishedModel("heroBannerComposition")]
	public partial class HeroBannerComposition : PublishedContentModel, IHeroBannerComposition
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.17.0")]
		public new const string ModelTypeAlias = "heroBannerComposition";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.17.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.17.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.17.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HeroBannerComposition, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public HeroBannerComposition(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// HeroBannerIImage
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.17.0")]
		[ImplementPropertyType("heroBannerIImage")]
		public virtual global::Umbraco.Core.Models.MediaWithCrops HeroBannerIimage => GetHeroBannerIimage(this);

		/// <summary>Static getter for HeroBannerIImage</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.17.0")]
		public static global::Umbraco.Core.Models.MediaWithCrops GetHeroBannerIimage(IHeroBannerComposition that) => that.Value<global::Umbraco.Core.Models.MediaWithCrops>("heroBannerIImage");

		///<summary>
		/// HeroBannerSubtitle
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.17.0")]
		[ImplementPropertyType("heroBannerSubtitle")]
		public virtual string HeroBannerSubtitle => GetHeroBannerSubtitle(this);

		/// <summary>Static getter for HeroBannerSubtitle</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.17.0")]
		public static string GetHeroBannerSubtitle(IHeroBannerComposition that) => that.Value<string>("heroBannerSubtitle");

		///<summary>
		/// HeroBannerTitle
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.17.0")]
		[ImplementPropertyType("heroBannerTitle")]
		public virtual string HeroBannerTitle => GetHeroBannerTitle(this);

		/// <summary>Static getter for HeroBannerTitle</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.17.0")]
		public static string GetHeroBannerTitle(IHeroBannerComposition that) => that.Value<string>("heroBannerTitle");
	}
}
